version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "HelloWorldStack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1kata4k3f6a0g"
s3_prefix = "HelloWorldStack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
